warmup5: warmup5.c warmup5_main.c warmup5_provided.c warmup5.h warmup5_provided.h
	clang -Wall -v -o warmup5 warmup5.c warmup5_main.c

hw5: hw5.c hw5_main.c hw5.h
	clang -Wall -o hw5 hw5.c hw5_main.c
